### ISSUE TITLE
Change license to MIT

### ISSUE THREAD

**Issue by Alexejhero** [Alexejhero/Neurosama-Subnautica-Mod#62]
This repository has no license, I would like to license it under MIT.
Please leave a comment stating that you agree with this change.

Contributor list:

- [x] @Alexejhero 
- [x] @Govorunb 
- [x] @w1n7er87 
- [x] @budwheizzah 
- [x] @jameshi16 
- [x] @Darkeew

**Comment by Darkeew** [comment]
👍

**Comment by jameshi16** [comment]
👍

**Comment by w1n7er87** [comment]
👍

**Comment by w1n7er87** [comment]
👍

**Comment by budwheizzah** [comment]
👍
